import { Transaction } from '@/types/transaction';

// Mock data for demonstration - will be replaced with real database queries
export const mockTransactions: Transaction[] = [
  {
    id: 'TX-2024-001234',
    type: 'electronics',
    buyerName: 'Juan D.',
    sellerName: 'Maria S.',
    price: 15000,
    currency: '₱',
    status: 'completed',
    location: 'Manila, Metro Manila',
    timestamp: new Date('2024-03-15T14:30:00'),
    platform: 'Facebook Marketplace',
    method: 'meetup', // <-- add this field
  },
  {
    id: 'TX-2024-001235',
    type: 'fashion',
    buyerName: 'Carlos M.',
    sellerName: 'Anna L.',
    price: 2500,
    currency: '₱',
    status: 'completed',
    location: 'Quezon City, Metro Manila',
    timestamp: new Date('2024-03-15T13:45:00'),
    platform: 'Carousell',
    method: 'meetup',
  },
  {
    id: 'TX-2024-001236',
    type: 'services',
    buyerName: 'Sofia R.',
    sellerName: 'Miguel P.',
    price: 5000,
    currency: '₱',
    status: 'completed',
    location: 'Makati, Metro Manila',
    timestamp: new Date('2024-03-15T12:20:00'),
    platform: 'Instagram',
    method: 'meetup',
  },
  {
    id: 'TX-2024-001237',
    type: 'home-goods',
    buyerName: 'Elena V.',
    sellerName: 'Ricardo T.',
    price: 8500,
    currency: '₱',
    status: 'completed',
    location: 'Pasig, Metro Manila',
    timestamp: new Date('2024-03-15T11:10:00'),
    platform: 'Facebook Marketplace',
    method: 'meetup',
  },
  {
    id: 'TX-2024-001238',
    type: 'electronics',
    buyerName: 'Luis G.',
    sellerName: 'Carmen F.',
    price: 25000,
    currency: '₱',
    status: 'completed',
    location: 'Taguig, Metro Manila',
    timestamp: new Date('2024-03-15T10:30:00'),
    platform: 'Carousell',
    method: 'meetup',
  },
  {
    id: 'TX-2024-001239',
    type: 'collectibles',
    buyerName: 'Andrea B.',
    sellerName: 'Jose C.',
    price: 12000,
    currency: '₱',
    status: 'completed',
    location: 'Cebu City, Cebu',
    timestamp: new Date('2024-03-15T09:15:00'),
    platform: 'Facebook Marketplace',
    method: 'meetup',
  },
  {
    id: 'TX-2024-001240',
    type: 'vehicles',
    buyerName: 'Marco A.',
    sellerName: 'Isabel N.',
    price: 180000,
    currency: '₱',
    status: 'completed',
    location: 'Davao City, Davao del Sur',
    timestamp: new Date('2024-03-14T16:45:00'),
    platform: 'Carousell',
    method: 'meetup',
  },
  {
    id: 'TX-2024-001241',
    type: 'fashion',
    buyerName: 'Patricia H.',
    sellerName: 'Roberto K.',
    price: 3200,
    currency: '₱',
    status: 'completed',
    location: 'Manila, Metro Manila',
    timestamp: new Date('2024-03-14T15:20:00'),
    platform: 'Instagram',
    method: 'meetup',
  },
];
